version: '3.8'
services:
  db:
    image: mysql:8.0.32
    container_name: database_inventario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_OUT_PORT}:${DB_PORT}
    volumes:
      - "${MOUNT_DIR}/data/db/:/var/lib/mysql"
  
  django:
    build:
      context: ${MOUNT_DIR}
      dockerfile: dockerfile
    container_name: api-inventario
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      STATIC_ROOT: ${STATIC_ROOT}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DB_ENGINE: ${DB_ENGINE}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        python /django/inventario/manage.py makemigrations --noinput
        python /django/inventario/manage.py migrate --noinput
        python /django/inventario/manage.py runserver 0.0.0.0:8080
    ports:
      - ${DJ_OUT_PORT}:8080
    volumes:
      - "${MOUNT_DIR}:/django/"
    depends_on:
      - db